@startuml "payment_components"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(payment_system, "[[https://github.com/acme-corp-tech/architecture/wiki/payment_system.svg Payment]]") {
    Container(payment_service, "Payment Service", "Go", "Integrates with external payment providers", $sprite="go")
}

@enduml
